type WeatherMeta = { label: string; icon: string };

export const weatherCodeMap: Record<number, WeatherMeta> = {
  0: { label: "Ясно", icon: "☀️" },
  1: { label: "Преимущественно ясно", icon: "🌤️" },
  2: { label: "Переменная облачность", icon: "⛅" },
  3: { label: "Облачно", icon: "☁️" },
  45: { label: "Туман", icon: "🌫️" },
  48: { label: "Изморозь, туман", icon: "🌫️" },
  51: { label: "Легкая морось", icon: "🌦️" },
  53: { label: "Морось", icon: "🌦️" },
  55: { label: "Сильная морось", icon: "🌧️" },
  56: { label: "Легкая морось с заморозками", icon: "🌧️" },
  57: { label: "Морось с заморозками", icon: "🌧️" },
  61: { label: "Небольшой дождь", icon: "🌧️" },
  63: { label: "Дождь", icon: "🌧️" },
  65: { label: "Сильный дождь", icon: "🌧️" },
  66: { label: "Ледяной дождь", icon: "🌧️" },
  67: { label: "Сильный ледяной дождь", icon: "🌧️" },
  71: { label: "Небольшой снег", icon: "❄️" },
  73: { label: "Снег", icon: "❄️" },
  75: { label: "Сильный снег", icon: "❄️" },
  77: { label: "Снежные зерна", icon: "❄️" },
  80: { label: "Небольшие ливни", icon: "🌧️" },
  81: { label: "Ливни", icon: "🌧️" },
  82: { label: "Сильные ливни", icon: "🌧️" },
  85: { label: "Небольшой снегопад", icon: "🌨️" },
  86: { label: "Сильный снегопад", icon: "🌨️" },
  95: { label: "Гроза", icon: "⛈️" },
  96: { label: "Гроза с градом", icon: "⛈️" },
  99: { label: "Гроза с сильным градом", icon: "⛈️" },
};
